#!/bin/bash

if [ $USER == root ]
	
	then
		echo "Root!"
		echo
	
	else
		echo "Vous devez le lancer en root!"
		exit
fi
		
case $1 in




#version
        "-version" | "-v" | "--version")
		#affiche les info de "allwinner".
                echo -e "Allwinner Tool By \e[91mD\e[33mo\e[93mc\e[92mt\e[94mo\e[35mr\e[39m_Titi for Linux"
				echo -e "\e[39mVersion 0.0.7 ALPHA"
                ;;
		
#help
        "-help")
		#Affiche ma miste de commande dispo
			cat /bin/hlp
			;;

#partition theorique

	"partition")
	#Affiche les partitions théorique
		cat /bin/part
		;;
	
#ADB

	"adb")
	#Installe les paquets android-tools*
	
	if [ -f /usr/bin/adb ]
	
	then
	
		#ADB est déjà installé

		echo
		
			if  [ -f /usr/bin/fastboot 	]
				then 
					echo "FASTBOOT et ADB sont déjà installés! :)"
				else
					echo "fastboot n'est pas installé"
					sudo apt-get install android-tools-fastboot
				fi
	
	else
		echo "ADB et FASTBOOT ne sont pas installé"
		sleep 3
		sudo apt-get install android-tools*
	fi
		;;


#usage

        *)
	#explication
        echo "Usage: allwinner [-version] [-help]"
	#salutation
	echo
		echo "Hey, salut $USERNAME!"
        ;;

esac

#EOF